// Generated by CoffeeScript 1.9.3
(function() {
  var BranchRect, DrawingCanvas, LeaveRect, Rectangle, Tree,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DrawingCanvas = (function() {
    function DrawingCanvas($el) {
      this.$el = $el;
      this.setSizes = bind(this.setSizes, this);
      this.el = this.$el[0];
      $(window).resize(this.setSizes);
      this.setSizes();
      this.ctx = this.el.getContext('2d');
    }

    DrawingCanvas.prototype.setSizes = function() {
      if (this.el.width !== this.$el.width()) {
        this.el.width = this.$el.width();
      }
      if (this.el.height !== this.$el.height()) {
        return this.el.height = this.$el.height();
      }
    };

    DrawingCanvas.prototype.clear = function(color) {
      this.ctx.fillStyle = color;
      return this.ctx.fillRect(0, 0, this.el.width, this.el.height);
    };

    return DrawingCanvas;

  })();

  $(function() {
    var branches, general, gui, leaves, tree;
    tree = new Tree;
    tree.generate();
    gui = new dat.GUI;
    branches = gui.addFolder('branches');
    branches.add(tree.branch_parameters, 'up_growing', 0, 100);
    branches.add(tree.branch_parameters, 'down_growing', 0, 100);
    branches.add(tree.branch_parameters, 'depth', 1, 10).step(1);
    branches.addColor(tree.branch_parameters, 'color');
    branches.add(tree.branch_parameters, 'hue_variance', 0, 20);
    branches.add(tree.branch_parameters, 'saturation_variance', 0, 50);
    branches.add(tree.branch_parameters, 'value_variance', 0, 50);
    leaves = gui.addFolder('leaves');
    leaves.add(tree.leaves_parameters, 'squareness', 0, 10).step(0.1);
    leaves.add(tree.leaves_parameters, 'depth', 0, 10).step(1);
    leaves.addColor(tree.leaves_parameters, 'color');
    leaves.add(tree.leaves_parameters, 'hue_variance', 0, 50);
    leaves.add(tree.leaves_parameters, 'saturation_variance', 0, 50);
    leaves.add(tree.leaves_parameters, 'value_variance', 0, 50);
    general = gui.addFolder('trunk');
    general.add(tree.trunk_parameters, 'width', 0, tree.trunk_parameters.width * 2);
    general.add(tree.trunk_parameters, 'height', 0, tree.trunk_parameters.width * 2);
    gui.add(tree.general_parameters, 'growing_time', 0, 1000);
    gui.addColor(tree.general_parameters, 'background');
    return gui.add(tree, 'generate');
  });

  Rectangle = (function() {
    function Rectangle(tree1, position1, size1, depth) {
      this.tree = tree1;
      this.position = position1;
      this.size = size1;
      this.depth = depth != null ? depth : 1;
      this.divide = bind(this.divide, this);
      this.currentTree = this.tree._currentTree;
    }

    Rectangle.prototype.draw = function(ctx) {
      this.ctx = ctx;
      this.setColors();
      this.ctx.fillStyle = "hsl(" + this.hue + ", " + (this.saturation * 100) + "%, " + (this.value * 100) + "%)";
      this.ctx.translate(this.position.x, this.position.y);
      this.ctx.rotate(-this.position.angle);
      this.ctx.fillRect(0, 0, this.size.width, -this.size.height);
      this.ctx.rotate(this.position.angle);
      return this.ctx.translate(-this.position.x, -this.position.y);
    };

    Rectangle.prototype.addAngle = Math.PI / 4;

    Rectangle.prototype.divide = function() {
      var i, len, rect, ref, results;
      if (this.currentTree !== this.tree._currentTree || this.depth >= this.tree.branch_parameters.depth + this.tree.leaves_parameters.depth) {
        return;
      }
      ref = this.childrenRect();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        rect = ref[i];
        rect.draw(this.ctx);
        results.push(setTimeout(rect.divide, jStat.exponential.sample(1 / this.tree.general_parameters.growing_time)));
      }
      return results;
    };

    Rectangle.prototype.childrenRect = function() {
      var leftRect, rightRect;
      leftRect = this.leftRect();
      rightRect = this.rightRect(leftRect);
      return [leftRect, rightRect];
    };

    Rectangle.prototype.isGoingDown = function(angle) {
      return Math.cos(angle) < 0;
    };

    Rectangle.prototype.leftRect = function() {
      var leftRectPosition, leftRectSize;
      leftRectPosition = {
        x: this.position.x + Math.cos(Math.PI / 2 + this.position.angle) * this.size.height,
        y: this.position.y - Math.sin(Math.PI / 2 + this.position.angle) * this.size.height,
        angle: this.position.angle + this.addAngle
      };
      leftRectSize = {
        width: this.size.width * Math.cos(this.addAngle),
        height: this.childHeight() * this.heightMultiplier(leftRectPosition)
      };
      if (this.depth >= this.tree.branch_parameters.depth) {
        return new LeaveRect(this.tree, leftRectPosition, leftRectSize, this.depth + 1);
      } else {
        return new BranchRect(this.tree, leftRectPosition, leftRectSize, this.depth + 1);
      }
    };

    Rectangle.prototype.rightRect = function(leftRect) {
      var rightRectPosition, rightRectSize;
      rightRectPosition = {
        x: leftRect.position.x + Math.cos(leftRect.position.angle) * leftRect.size.width,
        y: leftRect.position.y - Math.sin(leftRect.position.angle) * leftRect.size.width,
        angle: this.position.angle + this.addAngle - Math.PI / 2
      };
      rightRectSize = {
        width: this.size.width * Math.sin(this.addAngle),
        height: this.childHeight() * this.heightMultiplier(rightRectPosition)
      };
      if (this.depth >= this.tree.branch_parameters.depth) {
        return new LeaveRect(this.tree, rightRectPosition, rightRectSize, this.depth + 1);
      } else {
        return new BranchRect(this.tree, rightRectPosition, rightRectSize, this.depth + 1);
      }
    };

    Rectangle.prototype.setColors = function(rect_type) {
      var saturation_beta_parameter, saturation_inverse_variance, value_beta_parameter, value_inverse_variance;
      this.hue = jStat.normal.sample(this.tree[rect_type].color.h, this.tree[rect_type].hue_variance);
      saturation_beta_parameter = (1 - this.tree[rect_type].color.s) / this.tree[rect_type].color.s;
      saturation_inverse_variance = 51 - this.tree[rect_type].saturation_variance;
      this.saturation = jStat.beta.sample(saturation_inverse_variance, saturation_inverse_variance * saturation_beta_parameter);
      value_beta_parameter = (1 - this.tree[rect_type].color.v) / this.tree[rect_type].color.v;
      value_inverse_variance = 51 - this.tree[rect_type].value_variance;
      return this.value = jStat.beta.sample(value_inverse_variance, value_inverse_variance * value_beta_parameter);
    };

    return Rectangle;

  })();

  BranchRect = (function(superClass) {
    extend(BranchRect, superClass);

    function BranchRect() {
      return BranchRect.__super__.constructor.apply(this, arguments);
    }

    BranchRect.prototype.beta = 25;

    BranchRect.prototype.heightMultiplier = function(position) {
      if (this.isGoingDown(position.angle)) {
        return jStat.beta.sample(this.tree.branch_parameters.down_growing, this.beta);
      } else {
        return jStat.beta.sample(this.tree.branch_parameters.up_growing, this.beta);
      }
    };

    BranchRect.prototype.childHeight = function() {
      if (this.depth < this.tree.branch_parameters.depth) {
        return this.size.height;
      } else {
        return this.size.width;
      }
    };

    BranchRect.prototype.setColors = function() {
      return BranchRect.__super__.setColors.call(this, 'branch_parameters');
    };

    return BranchRect;

  })(Rectangle);

  LeaveRect = (function(superClass) {
    extend(LeaveRect, superClass);

    function LeaveRect() {
      return LeaveRect.__super__.constructor.apply(this, arguments);
    }

    LeaveRect.prototype.heightMultiplier = function(position) {
      return 1 + jStat.beta.sample(10.1 - this.tree.leaves_parameters.squareness, 10);
    };

    LeaveRect.prototype.childHeight = function() {
      return this.size.width;
    };

    LeaveRect.prototype.setColors = function() {
      return LeaveRect.__super__.setColors.call(this, 'leaves_parameters');
    };

    return LeaveRect;

  })(Rectangle);

  Tree = (function() {
    function Tree() {
      this.generate = bind(this.generate, this);
      var min;
      this.canvas = new DrawingCanvas($('canvas'));
      this.general_parameters = {
        growing_time: 200,
        background: "#ffffff"
      };
      min = Math.min(this.canvas.el.height, this.canvas.el.width);
      this.trunk_parameters = {
        width: min * 0.08,
        height: min * 0.08 * 16 / 9
      };
      this.branch_parameters = {
        up_growing: 50,
        down_growing: 50,
        depth: 7,
        color: {
          h: 40,
          s: 0.9,
          v: 0.3
        },
        hue_variance: 5,
        saturation_variance: 30,
        value_variance: 10
      };
      this.leaves_parameters = {
        depth: 4,
        squareness: 4,
        color: {
          h: 115,
          s: 0.9,
          v: 0.3
        },
        hue_variance: 10,
        saturation_variance: 10,
        value_variance: 10
      };
    }

    Tree.prototype.generate = function() {
      var rectPosition, size;
      this._currentTree = Math.random();
      this.canvas.clear(this.general_parameters.background);
      size = {
        width: this.trunk_parameters.width,
        height: this.trunk_parameters.height
      };
      rectPosition = {
        x: this.canvas.el.width / 2 - size.width / 2,
        y: this.canvas.el.height * 0.9,
        angle: 0
      };
      this.baseRect = new BranchRect(this, rectPosition, size);
      return this.draw();
    };

    Tree.prototype.draw = function() {
      this.baseRect.draw(this.canvas.ctx);
      return this.baseRect.divide();
    };

    return Tree;

  })();

}).call(this);
