// Generated by CoffeeScript 1.9.3
(function() {
  var BranchRect, DrawingCanvas, LeaveRect, Rectangle, Tree,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  DrawingCanvas = (function() {
    function DrawingCanvas($el) {
      this.$el = $el;
      this.setSizes = bind(this.setSizes, this);
      this.el = this.$el[0];
      $(window).resize(this.setSizes);
      this.setSizes();
      this.ctx = this.el.getContext('2d');
    }

    DrawingCanvas.prototype.setSizes = function() {
      if (this.el.width !== this.$el.width()) {
        this.el.width = this.$el.width();
      }
      if (this.el.height !== this.$el.height()) {
        return this.el.height = this.$el.height();
      }
    };

    DrawingCanvas.prototype.clear = function() {
      return this.ctx.clearRect(0, 0, this.el.width, this.el.height);
    };

    return DrawingCanvas;

  })();

  $(function() {
    var branches, general, gui, leaves, tree;
    tree = new Tree;
    tree.generate();
    gui = new dat.GUI;
    branches = gui.addFolder('branches');
    branches.add(tree, 'up_growing', 0, 100);
    branches.add(tree, 'down_growing', 0, 100);
    branches.add(tree, 'branch_depth', 1, 10).step(1);
    leaves = gui.addFolder('leaves');
    leaves.add(tree, 'squareness', 1, 10).step(1);
    leaves.add(tree, 'leaves_depth', 0, 10).step(1);
    general = gui.addFolder('general');
    general.add(tree, 'baseWidth', 0, tree.baseWidth * 2);
    general.add(tree, 'baseHeight', 0, tree.baseWidth * 2);
    general.add(tree, 'growingTime', 0, 1000);
    general.add(tree, 'generate');
    return general.open();
  });

  Rectangle = (function() {
    function Rectangle(tree1, position1, size1, depth) {
      this.tree = tree1;
      this.position = position1;
      this.size = size1;
      this.depth = depth != null ? depth : 1;
      this.divide = bind(this.divide, this);
      this.currentTree = this.tree._currentTree;
    }

    Rectangle.prototype.draw = function(ctx) {
      var brightness, hue;
      this.ctx = ctx;
      hue = this.hue + Math.random() * 20 - 10;
      brightness = Math.random() * 20 + 25;
      this.ctx.fillStyle = "hsl(" + hue + ", " + 90. + "%, " + brightness + "%)";
      this.ctx.translate(this.position.x, this.position.y);
      this.ctx.rotate(-this.position.angle);
      this.ctx.fillRect(0, 0, this.size.width, -this.size.height);
      this.ctx.rotate(this.position.angle);
      return this.ctx.translate(-this.position.x, -this.position.y);
    };

    Rectangle.prototype.addAngle = Math.PI / 4;

    Rectangle.prototype.divide = function() {
      var i, len, rect, ref, results;
      if (this.currentTree !== this.tree._currentTree || this.depth >= this.tree.branch_depth + this.tree.leaves_depth) {
        return;
      }
      ref = this.childrenRect();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        rect = ref[i];
        rect.draw(this.ctx);
        results.push(setTimeout(rect.divide, jStat.exponential.sample(1 / this.tree.growingTime)));
      }
      return results;
    };

    Rectangle.prototype.childrenRect = function() {
      var leftRect, rightRect;
      leftRect = this.leftRect();
      rightRect = this.rightRect(leftRect);
      return [leftRect, rightRect];
    };

    Rectangle.prototype.isGoingDown = function(angle) {
      return Math.cos(angle) < 0;
    };

    Rectangle.prototype.leftRect = function() {
      var leftRectPosition, leftRectSize;
      leftRectPosition = {
        x: this.position.x + Math.cos(Math.PI / 2 + this.position.angle) * this.size.height,
        y: this.position.y - Math.sin(Math.PI / 2 + this.position.angle) * this.size.height,
        angle: this.position.angle + this.addAngle
      };
      leftRectSize = {
        width: this.size.width * Math.cos(this.addAngle),
        height: this.childHeight() * this.heightMultiplier(leftRectPosition)
      };
      if (this.depth >= this.tree.branch_depth) {
        return new LeaveRect(this.tree, leftRectPosition, leftRectSize, this.depth + 1);
      } else {
        return new BranchRect(this.tree, leftRectPosition, leftRectSize, this.depth + 1);
      }
    };

    Rectangle.prototype.rightRect = function(leftRect) {
      var rightRectPosition, rightRectSize;
      rightRectPosition = {
        x: leftRect.position.x + Math.cos(leftRect.position.angle) * leftRect.size.width,
        y: leftRect.position.y - Math.sin(leftRect.position.angle) * leftRect.size.width,
        angle: this.position.angle + this.addAngle - Math.PI / 2
      };
      rightRectSize = {
        width: this.size.width * Math.sin(this.addAngle),
        height: this.childHeight() * this.heightMultiplier(rightRectPosition)
      };
      if (this.depth >= this.tree.branch_depth) {
        return new LeaveRect(this.tree, rightRectPosition, rightRectSize, this.depth + 1);
      } else {
        return new BranchRect(this.tree, rightRectPosition, rightRectSize, this.depth + 1);
      }
    };

    return Rectangle;

  })();

  BranchRect = (function(superClass) {
    extend(BranchRect, superClass);

    function BranchRect() {
      return BranchRect.__super__.constructor.apply(this, arguments);
    }

    BranchRect.prototype.hue = 40;

    BranchRect.prototype.heightMultiplier = function(position) {
      if (this.isGoingDown(position.angle)) {
        return jStat.beta.sample(this.tree.down_alpha, this.tree.down_beta);
      } else {
        return jStat.beta.sample(this.tree.up_alpha, this.tree.up_beta);
      }
    };

    BranchRect.prototype.childHeight = function() {
      if (this.depth < this.tree.branch_depth) {
        return this.size.height;
      } else {
        return this.size.width;
      }
    };

    return BranchRect;

  })(Rectangle);

  LeaveRect = (function(superClass) {
    extend(LeaveRect, superClass);

    function LeaveRect() {
      return LeaveRect.__super__.constructor.apply(this, arguments);
    }

    LeaveRect.prototype.hue = 115;

    LeaveRect.prototype.heightMultiplier = function(position) {
      return jStat.beta.sample(this.tree.squareness * 2, this.tree.squareness * 2);
    };

    LeaveRect.prototype.childHeight = function() {
      return this.size.width;
    };

    return LeaveRect;

  })(Rectangle);

  Tree = (function() {
    function Tree() {
      this.generate = bind(this.generate, this);
      var min;
      this.canvas = new DrawingCanvas($('canvas'));
      min = Math.min(this.canvas.el.height, this.canvas.el.width);
      this.baseWidth = min * 0.08;
      this.baseHeight = min * 0.08 * 16 / 9;
      this.growingTime = 200;
      this.up_growing = 50;
      this.down_growing = 50;
      this.branch_depth = 7;
      this.leaves_depth = 4;
      this.squareness = 4;
    }

    Tree.prototype.generate = function() {
      var rectPosition, size;
      this._calculateGrowing();
      this._currentTree = Math.random();
      this.canvas.clear();
      size = {
        width: this.baseWidth,
        height: this.baseHeight
      };
      rectPosition = {
        x: this.canvas.el.width / 2 - size.width / 2,
        y: this.canvas.el.height * 0.9,
        angle: 0
      };
      this.baseRect = new BranchRect(this, rectPosition, size);
      return this.draw();
    };

    Tree.prototype.draw = function() {
      this.baseRect.draw(this.canvas.ctx);
      return this.baseRect.divide();
    };

    Tree.prototype._calculateGrowing = function() {
      this.up_alpha = this.up_growing;
      this.up_beta = 25;
      this.down_alpha = this.down_growing;
      return this.down_beta = 25;
    };

    return Tree;

  })();

}).call(this);
